### ISSUE TITLE
caching static files with CachedStaticFilesStorage

### ISSUE THREAD

**Issue by amateja** [asyncee/django-easy-select2#24]
Hi,

I use your package and I want to have my static files cached but when I have no static files collected, empty cache and `DEBUG` set to `False` I end up with such exception using any of `manage.py` commands:
```
$ python manage.py 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/somewhere/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/somewhere/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/somewhere/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/somewhere/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/somewhere/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/somewhere/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/somewhere/lib/python3.4/site-packages/easy_select2/__init__.py", line 6, in <module>
    from easy_select2.utils import (
  File "/somewhere/lib/python3.4/site-packages/easy_select2/utils.py", line 7, in <module>
    from easy_select2.widgets import Select2Mixin, Select2, Select2Multiple
  File "/somewhere/lib/python3.4/site-packages/easy_select2/widgets.py", line 32, in <module>
    static('easy_select2/js/init.js'),
  File "/somewhere/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "/somewhere/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/somewhere/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'easy_select2/js/init.js' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x000000000000>.
```

My workaround is to set `DEBUG` to `True`, run `python manage.py collectstatic`, set it back to `False`. I use Django 1.8.8 and django-easy-select 1.3.1.

This works:
```python
DEBUG = True
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'
```
or
```python
DEBUG = False
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'  # default
```

This doesn't:
```python
DEBUG = False
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'
```

Running `python manage.py collectstatic` with `CachedStaticFilesStorage` to collect static files requires static files to be [already collected](https://github.com/django/django/blob/stable/1.8.x/django/contrib/staticfiles/storage.py#L131) :smile: as opposed to [default](https://github.com/django/django/blob/stable/1.8.x/django/core/files/storage.py#L315) `StaticFilesStorage`.

**Comment by kevin-brown** [comment]
To be more specific (and probably clarify things), the issue here is not with the `CachedStaticFilesStorage`, it's an issue with how the static file pathes are being determined _at import time_ instead of when they need to be used.

Calling `static`, [like is done at the top of `widgets.py`](https://github.com/asyncee/django-easy-select2/blob/b9607495c73d44bcc06ff025872def6d74513ac2/easy_select2/widgets.py#L32) requires that the file that you are trying to resolve has already been collected. Because the `widgets.py` submodule is imported by `utils.py` and the `__init__.py`, the static file location will need to be determined any time `easy_select2` is referenced. Django imports all modules in your `INSTALLED_APPS` at the start of management commands (among other places), so these lines will be executed before anyone can actually try to collect the static files.

The solution requires not determining the location of the static files at import time, which in this case is as easy as not calling `static`. Django should automatically resolve the paths of the static files when the assets are rendered. Even if this is not the case, you can [dynamically define the assets](https://docs.djangoproject.com/en/1.9/topics/forms/media/#media-as-a-dynamic-property).

**Comment by asyncee** [comment]
Hello, guys and thanks you for bug report. I must admin that configuring static files at import time was not the best decision (premature optimization). I think that the fix will be simple - refactor code to determine static paths dynamically using media as a property, as @kevin-brown has referenced higher.

I will be happy to accept merge request (including tests) before holidays, because i'm too busy this week - if you need fixed release as soon as possible, or i will try to fix it at weekend.

**Comment by amateja** [comment]
No rush if you ask me. I can live with it and I do. Just sharing my problem with you. Thank you for your openness and quick reaction. I could make pull request but not at this moment. Anyway I tried to prepare thorough problem report to let you understand easily where is the rub and to start discussion before not after :smile:.

What interests me the most is to find all fixes on pypi. Can be?

**Comment by asyncee** [comment]
Sure, i will publish 1.3.2 on pypi after fixing the issue :)
11 янв. 2016 г. 23:07 пользователь "Andrzej Mateja" <
notifications@github.com> написал:

**Comment by asyncee** [comment]
Thank you, version 1.3.2 released.
