### ISSUE TITLE
app breaks dumpdata

### ISSUE THREAD

**Issue by ZoltanOnody** [asyncee/django-easy-select2#29]
After adding `'easy_select2'`  to installed apps I am not able to run the `python manage.py dumpdata` command anymore. 

It says:
`CommandError: Unable to serialize database: no such table: easy_select2_related`

if I run it with traceback I get:
```
Traceback (most recent call last):
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: easy_select2_related

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/management/commands/dumpdata.py", line 167, in handle
    object_count=object_count)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/serializers/base.py", line 79, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/core/management/commands/dumpdata.py", line 150, in get_objects
    for obj in queryset.iterator():
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/zoli/projects/test_de2/venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: easy_select2_related
```

Python version: `Python 3.5.1+`
Installed packages: 
```
Django==1.9.7
django-easy-select2==1.3.2
pkg-resources==0.0.0
```

This app has `models.py` but no migrations so I tried to `makemigrations` and run them but it didn't help.

**Comment by jungornti** [comment]
This application has no migrations, because it has no models.

If you look at [source](https://github.com/asyncee/django-easy-select2/blob/master/easy_select2/models.py), you will see that you created migrations for test unmanaged models, which is wrong.

What you should do:

1. delete migrations you created manually
2. clear any application records in django_migrations table in your database

Now it should work.

**Comment by ZoltanOnody** [comment]
Nope. The error had been there before I created the migrations so the problem is somewhere else.

**Comment by asyncee** [comment]
I reproduced the problem on fresh django installation.

For now you can avoid this error using `exclude` parameter:

`./manage.py dumpdata --exclude easy_select2`

I need to somehow refactor tests to remove unmanaged models.

**Comment by asyncee** [comment]
Added bugs and workarounds section to readme for sometime before i get to this trouble.
